### ISSUE TITLE
Broken link in `requirements.txt`

### ISSUE THREAD

**Issue by jonchoi** [dternyak/React-Redux-Flask#13]
http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.1.3.zip

**Comment by alexcybernetic** [comment]
psycopg2==2.7.1 (instead of psycopg2==2.6.2)

**Comment by jonchoi** [comment]
think you misread my comment. link in requirements is broken.

![image](https://cloud.githubusercontent.com/assets/9872658/24572686/d844820a-162f-11e7-818f-a6fe27e516c4.png)

**Comment by alexcybernetic** [comment]
sorry, I mean psycopg2==2.6.2 in requirements.txt is also outdated and doesn't work. should be replaced with psycopg2==2.7.1

**Comment by dternyak** [comment]
These are both fixed now.
