### ISSUE TITLE
requirements.txt fails to install mysql-connector

### ISSUE THREAD

**Issue by imecimore** [dternyak/React-Redux-Flask#20]
Right now, http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.1.4.zip is giving a 404 - so installing requirements fails.

That line should probably be mysql-connector==2.1.4

**Comment by dternyak** [comment]
Thanks, if you open a PR I will merge it.

**Comment by dternyak** [comment]
Fixed by https://github.com/dternyak/React-Redux-Flask/commit/bfcf38010adb0b55b8028b3f58580788760fa889
