### ISSUE TITLE
Heroku building /dist

### ISSUE THREAD

**Issue by imecimore** [dternyak/React-Redux-Flask#23]
I don't think the javascript is getting built when deploying to Heroku.  Is there a special build pack that you are using?  I've had issues when the package.json file isn't in the root directory.

When I deploy the app, I get 404s for several static files when I navigate to the home page.

**Comment by dternyak** [comment]
I'm not super familiar with heroku so I'm not sure why that might be.

Let me know if you find a fix. Would appreciate a PR.
