### ISSUE TITLE
Invalid Salt

### ISSUE THREAD

**Issue by mmdonaldson** [dternyak/React-Redux-Flask#26]
Running this on windows and I've had a few issues with dependencies I have gotten around.

But whenever I create a new user, logout, and then try to log back in I get the same error.

with the get_user_with_email_and_password function it throws an error Invalid salt.

**Comment by dternyak** [comment]
Could you post a specific error message? I haven't used this boilerplate on windows, and I don't use windows in general, so I can't be of much help without more information.

**Comment by mmdonaldson** [comment]
@dternyak it seemed to fix itself when i downgraded to python 2.7 and remove the decode() function in generate_token.

I will close this for now. When I get a chance i'll go back over what I did, there's a few windows specific fixes I could add in a PR if you like?

**Comment by dternyak** [comment]
That would be great! Thanks.
