### ISSUE TITLE
Importing flask.ext.bcrypt is deprecated, use flask_bcrypt instead

### ISSUE THREAD

**Issue by animysore** [dternyak/React-Redux-Flask#29]
In index.py, import from flask_bcrypt instead of flask.ext.bcrypt

I made a pull request.

**Comment by dternyak** [comment]
Thanks -- merged https://github.com/dternyak/React-Redux-Flask/pull/30

**Comment by felexkemboi** [comment]
nice one,had the same problem only to be solved by getting  rid of the .ext thing
