### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by chppppp** [dternyak/React-Redux-Flask#41]
I know writing docs sucks buuuuut, would love a newbie guide for this awesome repo! Feel free to close this with prejudice :) 

Thanks

**Comment by dternyak** [comment]
What kind of documentation would be helpful for you?

**Comment by chppppp** [comment]
Wow thanks for the reply! I assumed I would never hear back :) 

A lot of these types of projects will sometimes include a blog on the setup and some details for newbs. It would be really awesome if such a post existed for this. I just got finished giving up on combining Flask+Vue (the {{ }} issues were a PITA and the blog posts were all incorrect/outdated), it would be nice for newbs like me to have a post to walk through the how-it-works for this. 

I know this request is a lot of work so feel free to close.

**Comment by dternyak** [comment]
Of course, thanks for opening this issue up. I would love to help devs like yourself get up and running with a full-stack and production ready boilerplate, as I know first-hand how challenging it can be to glue all the components together.

You're definitely right that there's a significant amount of work involved to develop these type of educational resources.

Hypothetically, do you think you (or folks like yourself) would be willing to pay for a tutorial series + production ready codebase?

**Comment by chppppp** [comment]
Personally, I would rather pay for 1:1 mentoring/tutoring than educational resources. I have blown enough money on coursera/udemy/etc on crappy courses to the point I am feeling pretty burned on it. However, that doesnt mean there isnt a huge market for these materials. I can imagine folks would pay for your course after seeing how popular your repo here is. 

I wont get into the whole video series vs. written docs bit on it ;) I personally prefer written docs with screenshots, but I am sure many newbs today prefer video series. 

I will send you an email to the address in your profile, if you are interested in doing some mentoring I would love to pay for your time and expertise (assuming it's in my price range :D)
