### ISSUE TITLE
Why is there an express server in static?

### ISSUE THREAD

**Issue by ZeroEcks** [dternyak/React-Redux-Flask#5]
I am pretty new to javascript but am I wrong that server.js is an express server?

Why is it there when you have a flask server?

**Comment by dternyak** [comment]
There are indeed 2 separate servers here -

The flask server is the backend. It handles interaction with the database and everything else that goes on in server-land.

The front-end server handles watching your front-end code for file changes and transpiling and  proxying requests from `localhost:3000` (the port the front-end server is running on) to `localhost:8080` (the back-end flask server) among other things.

Hope that answers your question.

**Comment by ZeroEcks** [comment]
Assuming you compile all the javascript, could it run fine with just the flask server?

**Comment by dternyak** [comment]
Yes exactly.

**Comment by ZeroEcks** [comment]
Thanks for the explanation.
